import React from 'react';

const Head = () => {
  return (
    <>
      <title> Task</title>
      <meta name="description" content="Generated by create Metwally Sayed" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
};

export default Head;
